### ISSUE TITLE
Unable to execute script

### ISSUE THREAD

**Issue by gjelsoe** [TonyWhitley/rF2headlights#1]
Getting a Unable to execute script if rF2headlights is started when rFactor2 is running..

**Comment by TonyWhitley** [comment]
No idea!   I tried turning off the Shared Memory plug in, that could have been a cause, but it ran fine, it just doesn't do anything.

Can you try the previous debug version https://github.com/TonyWhitley/rF2headlights/releases/download/V0.4.48/rF2headlightsDEBUG.exe which leaves the monitor window open as the program is starting up, there may be a clue in there.  Thanks.

**Comment by gjelsoe** [comment]
Perhaps this can help you 
import 'gui' # <pyimod03_importers.FrozenImporter object at 0x0000000000B549B0>
Traceback (most recent call last):
  File "rF2headlights.py", line 298, in <module>
  File "rF2headlights.py", line 52, in main
  File "gui.py", line 700, in gui_main
  File "gui.py", line 152, in __init__
  File "gui.py", line 628, in __init__
  File "gui.py", line 655, in __tick
  File "pyRfactor2SharedMemory\sharedMemoryAPI.py", line 165, in driverName
  File "pyRfactor2SharedMemory\sharedMemoryAPI.py", line 193, in Cbytestring2Python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 9: invalid start byte
[7228] Failed to execute script rF2headlights
[7228] LOADER: OK.
[7228] LOADER: Cleaning up Python interpreter.

**Comment by TonyWhitley** [comment]
Thanks, that gives me to something to work on.

**Comment by TonyWhitley** [comment]
OK, that's a driver name with ø.  I have changed the code to cope with different codepages, I just have to create a new release without some later changes I'm still working on - struggling with that at the moment!

**Comment by TonyWhitley** [comment]
https://github.com/TonyWhitley/rF2headlights/releases/tag/V0.6.54  Should fix it, there's a debug version as well if it doesn't

**Comment by gjelsoe** [comment]
Working.

**Comment by TonyWhitley** [comment]
Thanks for your help :)
